name: CI Workflow for automated build and testing of Tartan Home System

on:
    push:
    pull_request:

jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./smart-home

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Build Project
          run: |
            docker compose up -d

        - name: Clean up
          run: |
            docker compose down

    tests:
      runs-on: ubuntu-latest
      needs: build
      defaults:
        run:
          working-directory: ./smart-home/Platform

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup java 21 SDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Run JUnit
          working-directory: ./smart-home/Platform
          run: |
            ./gradlew test
