name: Run Tests
run-name: running tests
on:
  workflow_dispatch:
  push:

# from gradle's documentation https://docs.gradle.org/current/userguide/github-actions.html
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Run tests with Gradle Wrapper
        working-directory: ./smart-home/Platform
        run: ./gradlew test